// <auto-generated />
namespace GH.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCmsPage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCmsPage));
        
        string IMigrationMetadata.Id
        {
            get { return "201605050424008_AddCmsPage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
